### ISSUE TITLE
[feat] 작업 전 기본 도메인 및 계층 세팅

### ISSUE THREAD

**Issue by tkdwns414** [OMZigak/KKUM_SERVER#11]
## Issue 📌
[//]: # (전체 작업에 대해 간략한 설명)
Entity 생성, Repository 생성, Service 생성(Service는 CRUD Helper까지 같이 적용)

## Todo ✔️
[//]: # (해야할 일 간단한 체크리스트)
- [ ] User 엔티티, 레포지토리, 서비스 생성
- [ ] UserInfo 엔티티, 레포지토리, 서비스 생성
- [ ] Member 엔티티, 레포지토리, 서비스 생성
- [ ] Meeting 엔티티, 레포지토리, 서비스 생성
- [ ] Promise 엔티티, 레포지토리, 서비스 생성
- [ ] Participant 엔티티, 레포지토리, 서비스 생성
